name: Deploy Backend to Azure Functions

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

env:
  AZURE_FUNCTIONAPP_NAME: <YOUR_FUNCTION_APP_NAME> # Replace with your Azure Function App name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'Backend' # Set this to the path to your function app project, relative to repository root
  AZURE_RESOURCE_GROUP: <YOUR_RESOURCE_GROUP_NAME> # Replace with your Azure Resource Group name
  DOTNET_VERSION: '8.0.x' # Set this to the .NET version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      - name: Build project
        run: dotnet build ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} --configuration Release --no-build --output '${{ runner.temp }}/publish'

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Function App
        uses: azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
          package: '${{ runner.temp }}/publish'
          # Note: For dotnet-isolated, ensure FUNCTIONS_WORKER_RUNTIME is set in Azure Function App settings
          # az functionapp config appsettings set --name <app-name> --resource-group <resource-group> --settings FUNCTIONS_WORKER_RUNTIME=dotnet-isolated