# backend-deploy.yml

name: Build and Deploy .NET Backend

on:
  push:
    branches:
      - main
    paths:
      - 'IOT-python-simulator/UserService/**'
      - '.github/workflows/backend-deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Build and publish .NET app
        run: |
          dotnet restore IOT-python-simulator/UserService/UserService.csproj
          dotnet build IOT-python-simulator/UserService/UserService.csproj --configuration Release --no-restore
          dotnet publish IOT-python-simulator/UserService/UserService.csproj -c Release -o ./publish --no-build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sw-iot-2506-backend-api'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './publish'
